[build]
  command = "npm run build"
  functions = "dist/functions"

[[redirects]]
  from = "https://ahegao.netlify.com/*"
  to = "https://ahegao.egecelikci.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/random"
  to = "/.netlify/functions/random"
  status = 200
