[build]
  command = "#"
  functions = "functions/"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/random"
  to = "/.netlify/functions/random"
  status = 200
